/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include "unistd.h"

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 160
#define YY_END_OF_BUFFER 161
static yyconst short int yy_accept[440] =
    {   0,
      154,  154,    0,    0,    0,    0,   45,   45,    0,    0,
      161,  159,   59,   60,  101,  159,   63,   97,   98,  159,
       86,   87,   95,   93,   94,  105,   96,  154,  154,   85,
       84,   89,   92,   88,  158,  102,  103,  100,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,   82,   99,   83,  159,   25,
       27,   26,   29,   28,   30,   58,   33,   31,   49,   58,
       58,   56,   57,   45,   58,   45,   45,   50,   58,   51,
       47,   47,   47,   47,   47,   47,   58,   23,    3,    4,
        1,    2,   23,   23,   23,   23,   23,   23,   23,   23,

       59,   81,    0,    0,  152,    0,   70,   79,   71,    0,
        0,  157,    0,   68,   66,   64,   67,  155,  155,   65,
      104,  154,   62,  153,   69,  154,  154,  158,  156,   76,
       91,   78,   90,   77,   73,  158,  158,  158,  158,  158,
      158,  158,  134,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  123,  158,  137,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,   72,   80,    0,   25,   24,   29,   33,
        0,    0,   43,    0,   55,   45,   32,   45,   45,   47,
       46,    0,    0,   52,   44,    0,   48,   53,   47,   47,

       47,   47,   38,   47,   47,   54,    3,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  152,    0,    0,  157,    0,  155,  155,  154,  156,
       74,   75,  158,  158,  158,  158,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  133,  158,  158,  118,
      158,  108,  158,  151,  158,  117,  158,  158,  158,  114,
      158,  158,  158,  158,  158,  158,  158,  158,  138,  116,
      158,  158,   61,    0,   43,    0,   45,   46,    0,   44,
        0,   41,   47,   47,   47,   47,   47,   47,   11,    0,
        0,    0,    0,    0,   14,    7,    0,   22,   13,    6,

       10,    0,    0,   12,  155,  158,  158,  130,  158,  106,
      158,  158,  158,  158,  124,  158,  158,  158,  158,  158,
      158,  122,  158,  158,  115,  109,  158,  158,  158,  158,
      158,  158,  158,  158,  158,  158,  158,  113,  158,   47,
       39,   47,   47,   47,   47,   47,    0,   15,   18,   17,
       16,    0,    9,    0,  127,  132,  139,  144,  158,  158,
      158,  128,  158,  158,  110,  158,  158,  158,  158,  158,
      158,  158,  141,  158,  158,  107,  158,  158,  158,  158,
      158,  125,   47,   47,   40,   37,   47,   47,    5,    0,
        0,    0,    8,  158,  158,  111,  142,  158,  158,  158,

      147,  158,  158,  158,  158,  148,  140,  119,  158,  112,
      129,  158,   36,   42,   47,   35,   20,   19,   21,  158,
      131,  158,  136,  158,  158,  146,  149,  158,  120,  143,
       34,  135,  121,  126,  158,  158,  145,  150,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,    8,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,    8,    8,   26,   26,   26,   26,   26,   26,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   27,    8,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,   61,    8,    8,    8,
       62,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,   63,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    2,    1,    1,    4,    1,    4,    4,
        1,    1,    1,    1,    1,    4,    4,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    1,    1,    1,
        1,    1,    1
    } ;

static yyconst short int yy_base[455] =
    {   0,
        0,    0,   61,   62,   63,   64,   78,    0,  140,  189,
      973,  974,   66,  974,  948,  147,  974,  947,  135,  153,
      974,  974,  946,  136,  178,   52,  143,  146,  151,  974,
      974,   50,  945,  153,  951,  974,  974,  943,  156,  163,
      183,  171,  188,  203,  162,  189,  215,  202,  192,  221,
      201,  227,  196,  233,  230,  974,  145,  974,  905,    0,
      974,  947,    0,  974,  974,  974,  212,  974,  974,  255,
      954,  974,  974,  244,  945,  257,  268,  289,  938,  937,
      943,  251,  258,  237,  272,  254,  900,  974,  291,  974,
      974,  974,  923,  137,  106,  260,  905,  920,  250,  247,

      303,  974,  318,  324,  974,  330,  974,  974,  974,  337,
      340,  343,  354,  974,  974,  974,  974,  291,  344,  974,
      974,  296,  974,  974,  974,  303,  351,  938,  367,  930,
      974,  974,  974,  929,  974,  289,  341,  345,  317,  318,
      283,  357,  234,  335,  356,  358,  361,  291,  359,  362,
      363,  172,  935,  193,  364,  365,  372,  373,  371,  389,
      380,  381,  395,  393,  396,  374,  400,  405,  402,  404,
      407,  410,  415,  974,  974,  889,    0,  974,    0,  432,
      437,  445,  974,  456,  974,  434,  974,  444,  448,  933,
      469,  468,  489,  497,  506,  509,  974,  974,  477,  424,

      463,  461,  502,  499,  455,  974,  471,  914,  903,  487,
      894,  899,  913,  897,  900,  888,  894,  890,  893,  905,
      538,  544,  550,  557,  560,  563,  457,  462,  464,    0,
      974,  974,  510,  511,  500,  538,  531,  507,  503,  553,
      558,  559,  532,  561,  564,  566,  565,  570,  567,  920,
      571,  573,  576,  919,  582,  918,  577,  579,  583,  917,
      585,  586,  588,  590,  589,  591,  593,  595,  916,  915,
      601,  597,  974,  640,  646,  652,  602,    0,  658,  661,
      664,  914,  599,  594,  639,  640,  607,  634,  974,  880,
      881,  877,  876,  890,  974,  974,  882,  974,  974,  974,

      974,  885,  874,  974,  654,  618,  660,  905,  661,  904,
      663,  665,  667,  668,  903,  671,  674,  675,  677,  678,
      679,  902,  680,  682,  901,  900,  684,  686,  681,  695,
      687,  689,  691,  707,  697,  698,  709,  899,  708,  703,
      898,  704,  716,  721,  717,  726,  863,  974,  877,  876,
      974,  861,  974,  874,  892,  891,  890,  889,  728,  729,
      730,  888,  732,  733,  887,  734,  735,  738,  739,  740,
      742,  745,  886,  746,  743,  885,  744,  747,  754,  757,
      765,  884,  750,  766,  883,  882,  610,  767,  974,  850,
      849,  860,  974,  768,  770,  878,  877,  774,  777,  778,

      876,  780,  783,  786,  781,  875,  874,  873,  784,  872,
      854,  785,  845,  841,  787,  838,  974,  974,  974,  789,
      817,  788,  812,  790,  792,  798,  796,  794,  690,  616,
      512,  462,  420,  416,  797,  801,  412,  350,  974,  836,
      840,  844,  848,  852,  148,  856,  860,  864,   65,  868,
      872,  876,  880,  884
    } ;

static yyconst short int yy_def[455] =
    {   0,
      439,    1,  440,  440,  441,  441,  439,    7,  442,  442,
      439,  439,  439,  439,  439,  443,  439,  439,  439,  444,
      439,  439,  439,  439,  439,  439,  439,  445,  445,  439,
      439,  439,  439,  439,  445,  439,  439,  439,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  439,  439,  439,  439,  446,
      439,  439,  447,  439,  439,  439,  439,  439,  439,  448,
      439,  439,  439,  439,  439,  449,  449,  450,  439,  439,
      449,  449,  449,  449,  449,  449,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  443,  443,  439,  451,  439,  439,  439,  444,
      444,  444,  452,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  445,  445,  445,  439,
      439,  439,  439,  439,  439,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  439,  439,  439,  446,  439,  447,  439,
      448,  448,  439,  453,  439,  439,  439,  439,  449,  449,
      449,  450,  450,  450,  450,  454,  439,  439,  449,  449,

      449,  449,  449,  449,  449,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      443,  443,  451,  444,  444,  452,  439,  439,  439,  129,
      439,  439,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  439,  448,  448,  453,  439,  191,  450,  450,
      454,  449,  449,  449,  449,  449,  449,  449,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  449,
      449,  449,  449,  449,  449,  449,  439,  439,  439,  439,
      439,  439,  439,  439,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  449,  449,  449,  449,  449,  449,  439,  439,
      439,  439,  439,  445,  445,  445,  445,  445,  445,  445,

      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      445,  445,  449,  449,  449,  449,  439,  439,  439,  445,
      445,  445,  445,  445,  445,  445,  445,  445,  445,  445,
      449,  445,  445,  445,  445,  445,  445,  445,    0,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439
    } ;

static yyconst short int yy_nxt[1038] =
    {   0,
       12,   13,   14,   13,   15,   16,   17,   12,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   35,   36,   12,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       35,   35,   48,   35,   49,   35,   50,   35,   51,   52,
       53,   35,   54,   55,   35,   35,   35,   56,   57,   58,
       12,   12,   59,   61,   61,   64,   64,  101,  190,  101,
      122,  122,  130,  131,   62,   62,   65,   65,   66,   67,
       68,   67,   69,   70,   66,   66,   66,   71,   66,   72,
       73,   66,   66,   66,   74,   75,   76,   77,   66,   66,

       78,   79,   80,   81,   81,   66,   66,   66,   66,   82,
       81,   81,   83,   84,   81,   81,   81,   85,   81,   81,
       81,   81,   81,   81,   86,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   66,   87,   66,   66,   66,
       66,   89,   90,   89,  108,  211,   91,  103,  103,  103,
      115,  128,  105,  110,  110,  110,  123,  212,  109,  116,
      124,   92,  126,  112,  127,  127,  125,  126,  174,  127,
      127,   93,  439,   94,   95,  106,  133,  134,  439,  439,
       96,  113,  209,   97,   98,  210,   99,  439,  439,  100,
       89,   90,   89,  117,  118,   91,  119,  119,  136,  439,

      129,  120,  121,  175,  439,  439,  142,  151,  439,  439,
       92,  137,  439,  180,  138,  180,  143,  439,  439,  439,
       93,  139,   94,   95,  152,  140,  250,  159,  141,   96,
      144,  439,   97,   98,  147,   99,  164,  439,  100,  251,
      145,  157,  146,  439,  170,  148,  439,  158,  149,  439,
      439,  153,  160,  439,  150,  181,  181,  181,  154,  155,
      183,  156,  186,  186,  171,  165,  166,  439,  173,  161,
      439,  162,  163,  188,  439,  189,  189,  167,  172,  201,
      168,  202,  169,  184,  188,  241,  189,  189,  439,  192,
      192,  192,  207,  200,  207,  217,  213,  219,  220,  439,

      199,  218,  205,  214,  101,  439,  101,  439,  203,  227,
      227,  191,  194,  195,  122,  122,  204,  196,  103,  103,
      103,  229,  229,  105,  103,  103,  103,  239,  233,  105,
      104,  104,  103,  439,  439,  222,  246,  110,  110,  110,
      110,  110,  110,  110,  110,  110,  106,  112,  237,  238,
      112,  439,  106,  112,  111,  111,  110,  439,  223,  110,
      228,  439,  119,  119,  225,  113,  439,  126,  113,  127,
      127,  113,  439,  439,  439,  439,  234,  439,  439,  439,
      439,  439,  226,  439,  242,  230,  230,  439,  439,  439,
      439,  243,  230,  240,  235,  236,  439,  439,  230,  230,

      230,  230,  230,  230,  254,  439,  248,  247,  244,  439,
      245,  439,  439,  249,  252,  253,  439,  255,  439,  258,
      439,  439,  257,  439,  256,  259,  439,  261,  439,  260,
      264,  439,  439,  180,  265,  180,  439,  181,  181,  181,
      439,  263,  183,  262,  267,  181,  181,  181,  266,  271,
      183,  268,  186,  186,  272,  270,  182,  182,  181,  269,
      283,  275,  277,  277,  188,  184,  189,  189,  192,  192,
      192,  439,  207,  184,  207,  227,  227,  439,  439,  439,
      305,  305,  229,  229,  276,  439,  288,  278,  278,  192,
      192,  192,  195,  439,  278,  285,  196,  192,  192,  192,

      278,  278,  278,  278,  278,  278,  192,  192,  192,  193,
      193,  192,  284,  195,  192,  439,  439,  196,  439,  439,
      282,  195,  291,  439,  292,  196,  439,  439,  439,  293,
      195,  294,  287,  280,  196,  308,  286,  281,  103,  103,
      103,  306,  307,  105,  103,  103,  103,  439,  439,  105,
      104,  104,  103,  312,  439,  222,  311,  110,  110,  110,
      110,  110,  110,  111,  111,  110,  106,  112,  110,  439,
      112,  309,  106,  225,  439,  439,  316,  439,  223,  310,
      439,  439,  439,  439,  313,  113,  439,  439,  113,  439,
      314,  226,  439,  439,  315,  439,  317,  319,  439,  439,

      320,  439,  439,  321,  439,  439,  439,  439,  324,  439,
      439,  439,  322,  439,  318,  439,  323,  439,  327,  326,
      277,  277,  334,  439,  325,  333,  439,  330,  337,  341,
      335,  328,  439,  329,  439,  338,  332,  331,  340,  339,
      181,  181,  181,  336,  415,  183,  181,  181,  181,  345,
      439,  183,  182,  182,  181,  439,  439,  275,  192,  192,
      192,  192,  192,  192,  193,  193,  192,  355,  184,  192,
      342,  346,  305,  305,  184,  344,  439,  439,  343,  439,
      276,  439,  195,  439,  439,  195,  196,  439,  280,  196,
      439,  439,  281,  439,  439,  439,  439,  439,  439,  357,

      439,  356,  439,  439,  359,  439,  439,  439,  364,  366,
      361,  439,  358,  439,  439,  370,  372,  371,  360,  439,
      439,  362,  363,  439,  439,  439,  373,  365,  368,  367,
      369,  380,  439,  439,  374,  375,  377,  439,  378,  376,
      381,  379,  439,  382,  439,  439,  439,  383,  439,  439,
      439,  439,  385,  384,  439,  439,  439,  386,  439,  439,
      439,  439,  439,  439,  398,  396,  439,  399,  387,  388,
      439,  395,  394,  439,  400,  402,  397,  403,  405,  406,
      408,  439,  439,  439,  439,  413,  439,  407,  401,  409,
      439,  410,  404,  439,  439,  411,  439,  439,  416,  439,

      439,  439,  439,  439,  439,  439,  439,  412,  439,  414,
      439,  425,  439,  439,  439,  423,  422,  439,  426,  420,
      421,  427,  431,  424,  432,  435,  429,  430,  439,  436,
      433,  428,  437,  439,  434,  438,   60,   60,   60,   60,
       63,   63,   63,   63,   88,   88,   88,   88,  104,  104,
      104,  104,  111,  111,  439,  111,  177,  439,  177,  177,
      179,  439,  179,  179,  182,  182,  182,  182,  193,  193,
      439,  193,  221,  221,  221,  221,  224,  224,  224,  224,
      274,  274,  274,  274,  279,  279,  279,  279,  439,  439,
      439,  439,  439,  439,  439,  419,  418,  417,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  393,
      392,  391,  390,  389,  439,  439,  439,  439,  439,  439,
      439,  439,  354,  353,  352,  351,  350,  349,  348,  347,
      439,  439,  439,  439,  439,  439,  439,  304,  303,  302,
      301,  300,  299,  298,  297,  296,  295,  290,  289,  439,
      273,  439,  232,  231,  439,  216,  215,  208,  206,  439,
      198,  197,  187,  185,  178,  176,  135,  439,  132,  114,
      107,  102,  439,   11,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439
    } ;

static yyconst short int yy_chk[1038] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    5,    6,   13,  449,   13,
       26,   26,   32,   32,    3,    4,    5,    6,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,

        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    9,    9,    9,   19,   95,    9,   16,   16,   16,
       24,  445,   16,   20,   20,   20,   27,   95,   19,   24,
       27,    9,   28,   20,   28,   28,   27,   29,   57,   29,
       29,    9,   39,    9,    9,   16,   34,   34,   45,   40,
        9,   20,   94,    9,    9,   94,    9,   42,  152,    9,
       10,   10,   10,   25,   25,   10,   25,   25,   39,   41,

       28,   25,   25,   57,   43,   46,   42,   45,   49,  154,
       10,   40,   53,   67,   41,   67,   42,   51,   48,   44,
       10,   41,   10,   10,   46,   41,  152,   49,   41,   10,
       43,   47,   10,   10,   44,   10,   51,   50,   10,  154,
       43,   48,   43,   52,   53,   44,   55,   48,   44,   54,
      143,   47,   50,   84,   44,   70,   70,   70,   47,   47,
       70,   47,   74,   74,   54,   52,   52,   82,   55,   50,
       86,   50,   50,   76,   83,   76,   76,   52,   54,   84,
       52,   84,   52,   70,   77,  143,   77,   77,   85,   78,
       78,   78,   89,   83,   89,   99,   96,  100,  100,  141,

       82,   99,   86,   96,  101,  136,  101,  148,   85,  118,
      118,   76,   78,   78,  122,  122,   85,   78,  103,  103,
      103,  126,  126,  103,  104,  104,  104,  141,  136,  104,
      106,  106,  106,  139,  140,  106,  148,  110,  110,  110,
      111,  111,  111,  112,  112,  112,  103,  110,  139,  140,
      111,  144,  104,  112,  113,  113,  113,  137,  106,  113,
      119,  138,  119,  119,  113,  110,  438,  127,  111,  127,
      127,  112,  145,  142,  146,  149,  137,  147,  150,  151,
      155,  156,  113,  129,  144,  129,  129,  159,  157,  158,
      166,  145,  129,  142,  138,  138,  161,  162,  129,  129,

      129,  129,  129,  129,  157,  160,  150,  149,  146,  164,
      147,  163,  165,  151,  155,  156,  167,  158,  169,  161,
      170,  168,  160,  171,  159,  161,  172,  163,  437,  162,
      166,  173,  434,  180,  167,  180,  433,  181,  181,  181,
      200,  165,  181,  164,  168,  182,  182,  182,  167,  172,
      182,  169,  186,  186,  173,  171,  184,  184,  184,  170,
      200,  184,  188,  188,  189,  181,  189,  189,  192,  192,
      192,  205,  207,  182,  207,  227,  227,  202,  432,  201,
      228,  228,  229,  229,  184,  191,  205,  191,  191,  193,
      193,  193,  192,  199,  191,  202,  192,  194,  194,  194,

      191,  191,  191,  191,  191,  191,  195,  195,  195,  196,
      196,  196,  201,  193,  196,  204,  235,  193,  203,  239,
      199,  194,  210,  238,  210,  194,  233,  234,  431,  210,
      195,  210,  204,  196,  195,  235,  203,  196,  221,  221,
      221,  233,  234,  221,  222,  222,  222,  237,  243,  222,
      223,  223,  223,  239,  236,  223,  238,  224,  224,  224,
      225,  225,  225,  226,  226,  226,  221,  224,  226,  240,
      225,  236,  222,  226,  241,  242,  243,  244,  223,  237,
      245,  247,  246,  249,  240,  224,  248,  251,  225,  252,
      241,  226,  253,  257,  242,  258,  244,  246,  255,  259,

      247,  261,  262,  248,  263,  265,  264,  266,  252,  267,
      284,  268,  249,  272,  245,  283,  251,  271,  257,  255,
      277,  277,  265,  287,  253,  264,  387,  261,  268,  284,
      266,  258,  430,  259,  306,  271,  263,  262,  283,  272,
      274,  274,  274,  267,  387,  274,  275,  275,  275,  287,
      288,  275,  276,  276,  276,  285,  286,  276,  279,  279,
      279,  280,  280,  280,  281,  281,  281,  306,  274,  281,
      285,  288,  305,  305,  275,  286,  307,  309,  285,  311,
      276,  312,  279,  313,  314,  280,  279,  316,  281,  280,
      317,  318,  281,  319,  320,  321,  323,  329,  324,  309,

      327,  307,  328,  331,  312,  332,  429,  333,  318,  320,
      314,  330,  311,  335,  336,  327,  329,  328,  313,  340,
      342,  316,  317,  334,  339,  337,  329,  319,  323,  321,
      324,  336,  343,  345,  330,  331,  333,  344,  334,  332,
      337,  335,  346,  339,  359,  360,  361,  340,  363,  364,
      366,  367,  343,  342,  368,  369,  370,  344,  371,  375,
      377,  372,  374,  378,  364,  361,  383,  366,  345,  346,
      379,  360,  359,  380,  367,  369,  363,  370,  372,  374,
      377,  381,  384,  388,  394,  383,  395,  375,  368,  378,
      398,  379,  371,  399,  400,  380,  402,  405,  388,  403,

      409,  412,  404,  415,  422,  420,  424,  381,  425,  384,
      428,  402,  427,  435,  426,  399,  398,  436,  403,  394,
      395,  404,  415,  400,  420,  425,  409,  412,  423,  428,
      422,  405,  435,  421,  424,  436,  440,  440,  440,  440,
      441,  441,  441,  441,  442,  442,  442,  442,  443,  443,
      443,  443,  444,  444,  416,  444,  446,  414,  446,  446,
      447,  413,  447,  447,  448,  448,  448,  448,  450,  450,
      411,  450,  451,  451,  451,  451,  452,  452,  452,  452,
      453,  453,  453,  453,  454,  454,  454,  454,  410,  408,
      407,  406,  401,  397,  396,  392,  391,  390,  386,  385,

      382,  376,  373,  365,  362,  358,  357,  356,  355,  354,
      352,  350,  349,  347,  341,  338,  326,  325,  322,  315,
      310,  308,  303,  302,  297,  294,  293,  292,  291,  290,
      282,  270,  269,  260,  256,  254,  250,  220,  219,  218,
      217,  216,  215,  214,  213,  212,  211,  209,  208,  190,
      176,  153,  134,  130,  128,   98,   97,   93,   87,   81,
       80,   79,   75,   71,   62,   59,   38,   35,   33,   23,
       18,   15,   11,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,

      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "stack.lex"
#define INITIAL 0
#line 2 "stack.lex"
/*=========================================================================
C-libraries and Token definitions
=========================================================================*/
#include <string.h> /* for strdup */
/*#include <stdlib.h> */ /* for atoi */
#include "token.h"
#include "stack_tab.h" /* for token definitions and yylval */
#include "lex_proto.h"
#include "sym_table.h"
#include "asm_streamer.h"

#define YY_INPUT(buf,result,max_size) { \
	int c = '*', n, d; \
	for ( n = 0; n < max_size && \
		     (c = pp_getc( p_config )) != EOF && c != '\n'; ++n ) \
		buf[n] = (char)(c); \
	if ( c == '\n' ) { \
        while((d = pp_getc( p_config )) == '\r' || d == '\n') { if( d=='\n' ) p_config->line++; }\
        if( d == EOF) {\
            pp_close( p_config);\
		    p_config = lp_pop_config();\
        } else {\
            pp_seek( p_config, -1, SEEK_CUR);\
		    buf[n++] = (char) c; \
        }\
	} \
	if ( c == EOF && pp_error(  p_config ) ) {\
		/*printf( "input in flex scanner failed\n" );*/ \
	}\
	if(p_config->show_assembly) {\
		as_info(_RECAST(uchar *, buf));	\
	}\
	if ( c == EOF) {\
		pp_close( p_config);\
		p_config = lp_pop_config();\
	}\
	result = n; \
	/*buf[n]=0;\
	printf("%s\n", buf);*/\
	if(result<=0) result=YY_NULL; \
}


/*=========================================================================
TOKEN Definitions
=========================================================================*/
#define BLOCK_COMMENT_SECTION 1

#define LINE_COMMENT_SECTION 2

#define PREPROCESSOR_SECTION 3

#define ASSEMBLER_SECTION 4

/*NUMBER [0-9]*  */
/*=========================================================================
REGULAR EXPRESSIONS defining the tokens for the Simple language
=========================================================================*/
#line 799 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 61 "stack.lex"

#line 952 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 440 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 974 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;


case 1:
YY_RULE_SETUP
#line 63 "stack.lex"
{ BEGIN(PREPROCESSOR_SECTION); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "stack.lex"
{ BEGIN(LINE_COMMENT_SECTION); } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "stack.lex"
{ /* eat up whitespace */ } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "stack.lex"
{ p_config->line++; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 67 "stack.lex"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "stack.lex"

	YY_BREAK
case 7:
YY_RULE_SETUP
#line 69 "stack.lex"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 70 "stack.lex"

	YY_BREAK
case 9:
YY_RULE_SETUP
#line 71 "stack.lex"

	YY_BREAK
case 10:
YY_RULE_SETUP
#line 72 "stack.lex"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 73 "stack.lex"

	YY_BREAK
case 12:
YY_RULE_SETUP
#line 74 "stack.lex"

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "stack.lex"

	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "stack.lex"

	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "stack.lex"

	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "stack.lex"

	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "stack.lex"

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "stack.lex"

	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "stack.lex"

	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "stack.lex"

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "stack.lex"

	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "stack.lex"

	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK


case 24:
YY_RULE_SETUP
#line 89 "stack.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 90 "stack.lex"
{ /* eat comment in chunks */ }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 91 "stack.lex"
{ /* eat the lone star */ }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 92 "stack.lex"
{ p_config->line++; }
	YY_BREAK


case 28:
YY_RULE_SETUP
#line 96 "stack.lex"
{ p_config->line++; BEGIN(INITIAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "stack.lex"
// eat comment in chunks
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "stack.lex"
// eat the lone star
	YY_BREAK


case 31:
YY_RULE_SETUP
#line 102 "stack.lex"
{ p_config->line++; lp_flush_token(); if(_lex_state != LEX_STATE_INVALID) BEGIN(INITIAL); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 103 "stack.lex"
{ lp_flush_token(); if(_lex_state != LEX_STATE_INVALID) BEGIN(LINE_COMMENT_SECTION); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 104 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 105 "stack.lex"
{ /*lp_preprocessor_state(LEX_STATE_INCLUDE);*/ }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 106 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_PRAGMA); 	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 107 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_DEFINE);  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 108 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_IFDEF); 	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 109 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_IF); 		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 110 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_ELSE); 	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 111 "stack.lex"
{ lp_preprocessor_state(LEX_STATE_ENDIF); 	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 112 "stack.lex"
{ BEGIN(ASSEMBLER_SECTION); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 113 "stack.lex"
{ BEGIN(INITIAL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 114 "stack.lex"
{ 
		uchar buffer[4096];
		uint16 length;
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, yytext + 1, strlen(yytext) - 2);
		length = lp_unescape(buffer, buffer);
		lp_process_token(buffer, length);
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 122 "stack.lex"
{ 
		uchar buffer[4096];
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, yytext + 1, strlen(yytext) - 2);
		lp_process_token(buffer, strlen((const char *)buffer));
	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 128 "stack.lex"
{
		lp_process_token(_RECAST(uchar *, yytext), strlen(_RECAST(const char *, yytext)));
	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 131 "stack.lex"
{ 				
		char buffer[1024];	
		memset(buffer, 0, sizeof(buffer));
		sprintf(buffer, "%i", lp_hex2integer(yytext + 2));
		lp_process_token((uchar *)buffer, strlen((const char *)buffer));
	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 137 "stack.lex"
{
		lp_process_token(_RECAST(uchar *, yytext), strlen(yytext));
	}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 140 "stack.lex"
{ lp_push_opcode(LEX_OP_EQ); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 141 "stack.lex"
{ lp_push_opcode(LEX_OP_NEG); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 142 "stack.lex"
{ lp_push_opcode(LEX_OP_LT); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 143 "stack.lex"
{ lp_push_opcode(LEX_OP_GT); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 144 "stack.lex"
{ lp_push_opcode(LEX_OP_LTEQ); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 145 "stack.lex"
{ lp_push_opcode(LEX_OP_GTEQ); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 146 "stack.lex"
{ lp_push_opcode(LEX_OP_OR); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 147 "stack.lex"
{ lp_push_opcode(LEX_OP_AND); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 148 "stack.lex"
{ /* ignore */ }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 149 "stack.lex"
{ /* ignore */ }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 150 "stack.lex"
{ /* eat up whitespace */ }
	YY_BREAK

case 59:
YY_RULE_SETUP
#line 153 "stack.lex"
{ /* eat up whitespace */ } 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 154 "stack.lex"
{ p_config->line++; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 155 "stack.lex"
{ /* eat up byte order mark */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 157 "stack.lex"
{ BEGIN(BLOCK_COMMENT_SECTION); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 158 "stack.lex"
{ BEGIN(PREPROCESSOR_SECTION); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 160 "stack.lex"
{ return S_ADDEQ; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 161 "stack.lex"
{ return S_SUBEQ; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 162 "stack.lex"
{ return S_ADDADD; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 163 "stack.lex"
{ return S_SUBSUB; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 164 "stack.lex"
{ return S_MULEQ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 165 "stack.lex"
{ return S_DIVEQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 166 "stack.lex"
{ return S_MODEQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 167 "stack.lex"
{ return S_ANDEQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 168 "stack.lex"
{ return S_OREQ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 169 "stack.lex"
{ return S_XOREQ; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 170 "stack.lex"
{ return S_SHLEQ; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 171 "stack.lex"
{ return S_SHREQ; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 173 "stack.lex"
{ return S_SHL; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 174 "stack.lex"
{ return S_SHR; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 175 "stack.lex"
{ return T_EQ; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 176 "stack.lex"
{ return T_AND; }	//type and
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 177 "stack.lex"
{ return T_OR; }	//type or
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 178 "stack.lex"
{ return T_NE; }	//type not equal
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 179 "stack.lex"
{ return L_CL; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 180 "stack.lex"
{ return R_CL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 181 "stack.lex"
{ return EOS; } 	//semicolon (end of statement)
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 182 "stack.lex"
{ return EOC; } 	//colon (end of label)
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 183 "stack.lex"
{ return L_BR; }	//left bracket
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 184 "stack.lex"
{ return R_BR; } 	//right bracket
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 185 "stack.lex"
{ return T_GT; }	//type greater than
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 186 "stack.lex"
{ return T_LT; }	//type less than
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 187 "stack.lex"
{ return T_GTEQ; }	//type greater than
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 188 "stack.lex"
{ return T_LTEQ; }	//type less than
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 189 "stack.lex"
{ return S_EQ; }	//type equal
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 190 "stack.lex"
{ return S_ADD; } 	
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 191 "stack.lex"
{ return S_SUB; } 	
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 192 "stack.lex"
{ return S_MUL; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 193 "stack.lex"
{ return S_DIV; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 194 "stack.lex"
{ return S_MOD; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 195 "stack.lex"
{ return S_AND; } 	
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 196 "stack.lex"
{ return S_OR; } 	
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 197 "stack.lex"
{ return S_XOR; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 198 "stack.lex"
{ return S_NOT; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 199 "stack.lex"
{ return L_SB; }	//left square bracket
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 200 "stack.lex"
{ return R_SB; } 	//right square bracket
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 201 "stack.lex"
{ return S_RNEXT; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 202 "stack.lex"
{ return S_PDOT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 204 "stack.lex"
{ return P_BYTE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 205 "stack.lex"
{ return P_HWORD; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 206 "stack.lex"
{ return P_WORD; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 207 "stack.lex"
{ return P_DWORD; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 208 "stack.lex"
{ return P_FLOAT; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 209 "stack.lex"
{ return P_DOUBLE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 210 "stack.lex"
{ return P_STRING; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 211 "stack.lex"
{ return P_VOID; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 212 "stack.lex"
{ return P_PTR; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 213 "stack.lex"
{ return P_AUTO; }		//intelligent pointer
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 215 "stack.lex"
{ return P_VAR; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 216 "stack.lex"
{ return P_NEW; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 217 "stack.lex"
{ return P_HEX; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 218 "stack.lex"
{ return P_SIZEOF; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 220 "stack.lex"
{ return P_STDCALL; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 221 "stack.lex"
{ return P_FASTCALL; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 223 "stack.lex"
{ return P_GOTO; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 224 "stack.lex"
{ return P_IF; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 225 "stack.lex"
{ return P_ELSE; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 226 "stack.lex"
{ return P_WHILE; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 227 "stack.lex"
{ return P_FUNCTION; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 228 "stack.lex"
{ return P_ALIAS; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 229 "stack.lex"
{ return P_EVENT; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 230 "stack.lex"
{ return P_SWITCH; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 231 "stack.lex"
{ return P_CASE; } 
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 232 "stack.lex"
{ return P_DEFAULT; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 233 "stack.lex"
{ return P_BREAK; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 234 "stack.lex"
{ return P_FOR; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 235 "stack.lex"
{ return P_DO; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 236 "stack.lex"
{ return P_CONTINUE; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 237 "stack.lex"
{ return P_FOREACH; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 238 "stack.lex"
{ return P_IN; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 239 "stack.lex"
{ return P_TRY; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 240 "stack.lex"
{ return P_CATCH; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 241 "stack.lex"
{ return P_RETURN; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 242 "stack.lex"
{ return P_PROTO; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 243 "stack.lex"
{ return P_EXTERN; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 244 "stack.lex"
{ return P_SYSCALL; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 246 "stack.lex"
{ return P_CLASS; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 247 "stack.lex"
{ return P_INTERFACE; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 248 "stack.lex"
{ return P_PACKAGE; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 249 "stack.lex"
{ return P_IMPORT; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 250 "stack.lex"
{ return P_PUBLIC; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 251 "stack.lex"
{ return P_PRIVATE; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 252 "stack.lex"
{ return P_PROTECTED; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 253 "stack.lex"
{ return P_LIB; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 255 "stack.lex"
{ 
	char buffer[4096];
	uint16 length;
	memset(buffer, 0, sizeof(buffer));
	memcpy(buffer, yytext + 1, strlen(yytext) - 2);
	memset(yylval.string, 0, sizeof(yylval.string));
	length = lp_unescape(_RECAST(uchar *, yylval.bytes.value), _RECAST(uchar *, buffer));
	yylval.bytes.length = length;
	return CONSTANT; 
}
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 266 "stack.lex"
{ BEGIN(LINE_COMMENT_SECTION); }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 268 "stack.lex"
{ 			
	char buffer[256];	
	memset(buffer, 0, sizeof(buffer));
	memcpy(buffer, yytext, strlen(yytext));
	memcpy((uchar *)(yylval.bytes.value), buffer, strlen(buffer) + 1);
	yylval.bytes.length = strlen(buffer);
	if(strstr(buffer, ".") != NULL) return NUMERIC;
	return CONSTANT; 
}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 278 "stack.lex"
{ 				
	char buffer[256];	
	memset(buffer, 0, sizeof(buffer));
	memcpy(buffer, yytext, strlen(yytext));
	memcpy((uchar *)(yylval.bytes.value), buffer, strlen(buffer) + 1);
	yylval.bytes.length = strlen(buffer);
	if(strstr(buffer, ".") != NULL) return N_NUMERIC;
	return N_CONSTANT;
}
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 288 "stack.lex"
{ 				
	char buffer[1024];	
	memset(buffer, 0, 256);
	sprintf(buffer, "%i", lp_hex2integer(yytext + 2));
	memcpy((uchar *)(yylval.bytes.value), buffer, strlen(buffer) + 1);
	yylval.bytes.length = strlen(buffer);
	return CONSTANT; 
}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 297 "stack.lex"
{ 
	char buffer[4096];
	uint16 length;
	memset(buffer, 0, sizeof(buffer));
	memcpy(buffer, yytext + 1, strlen(yytext) - 2);
	memset(yylval.string, 0, sizeof(yylval.string));
	length = lp_unescape(_RECAST(uchar *, yylval.bytes.value), _RECAST(uchar *, buffer));
	sprintf(_RECAST(char *, yylval.bytes.value), "%d", yylval.bytes.value[0]); 
	yylval.bytes.length = strlen(_RECAST(const char *, yylval.bytes.value));
	return CONSTANT; 
}
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 309 "stack.lex"
{	
	pp_const * pconst = NULL;
	symrec * var = NULL;
	char buffer[4096];
	uint32 offset = 0;
	pconst = lp_select(_RECAST(uchar *, yytext));			/* select from preprocessor constants */
	if(pconst == NULL) {
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, yytext, strlen(yytext));
		memcpy((uchar *)(yylval.string), buffer, strlen(buffer) + 1);
		return VARIABLE;
	} else {							/* preprocessor constant found */
		memset(buffer, 0, sizeof(buffer));
		memcpy(buffer, pconst->value, pconst->length);
		memcpy(_RECAST(uchar *, yylval.bytes.value), buffer, pconst->length);
		yylval.bytes.length = pconst->length;
		return CONSTANT;
	}	
}
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 329 "stack.lex"
{ return(yytext[0]); }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 330 "stack.lex"
ECHO;
	YY_BREAK
#line 1924 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BLOCK_COMMENT_SECTION):
case YY_STATE_EOF(LINE_COMMENT_SECTION):
case YY_STATE_EOF(PREPROCESSOR_SECTION):
case YY_STATE_EOF(ASSEMBLER_SECTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 440 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 440 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 439);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 330 "stack.lex"


int yywrap(void) { return -1; }

void yyinit(void) { 
	YY_FLUSH_BUFFER;
	BEGIN(INITIAL);	
}

/************************** End Scanner File *****************************/



